sudo: true

addons:
  apt:
    sources:
    - sourceline: 'deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse'
    packages:
    - shellcheck

services:
  - docker

before_install:
- sudo apt-get update
- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
- docker build -t gluster/client ./gluster-client/
- docker run -it --name client gluster/client rpm -qa | grep gluster
- docker build -t gluster/centos ./CentOS/
- docker run -d --name gcentos --privileged gluster/centos
- sleep 10
- docker exec -it gcentos systemctl is-active glusterd
- docker build -t gluster/fedora ./Fedora/
- docker run -d --name gfedora --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro gluster/fedora
- sleep 10
- docker exec -it gfedora systemctl is-active glusterd
- docker build -t gluster/s3object ./gluster-s3object/CentOS/docker-gluster-s3/
- docker run -d --name s3object --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro -e GLUSTER_VOLUMES=vol gluster/s3object
- sleep 10
- docker exec -it s3object systemctl is-active swift-object

script:
- make test
